'use strict';

export default {
  ActionTypes: {
    EDITOR_READY: "EDITOR_READY",
    EDITOR_SET_IMAGE: "EDITOR_SET_IMAGE",
    EDITOR_RELOAD: "EDITOR_RELOAD",
    EDITOR_CONTEXT_MENU: "EDITOR_CONTEXT_MENU",
    LOAD_METADATA: "LOAD_METADATA"
  }
};