/**
 * Created by dmitri on 15/01/16.
 */
'use strict';

export default {
  ActionTypes: {
    TOGGLE_SET_MANAGER_VISIBILITY: "MANAGER_TOGGLE_SEt_MANAGER_VISIBILITY",
    SET_SELECTED_NODE: 'MANAGER_SET_SELECTED_NODE',
    RELOAD_DISPLAYED_SETS: 'MANAGER_RELOAD_DISPLAYED_SETS',
    RELOAD: 'MANAGER_RELOAD',
    BASKET_CHANGE_SELECTION: 'MANAGER_BASKET_CHANGE_SELECTION',
    SET_BASKET: 'MANAGER_SET_BASKET',
    BASKET_REMOVE_ITEM: 'MANAGER_BASKET_REMOVE_ITEM',
    SET_ACTIVE_ENTITY_IN_SET: 'MANAGER_SET_ACTIVE_ENTITY_IN_SET',
    ADD_BASKET_ITEMS_TO_SET: 'MANAGER_ADD_BASKET_ITEMS_TO_SET'
  }
};