/**
 * Created by dmitri on 15/01/16.
 */
'use strict';

export default {
  ActionTypes: {
    TOGGLE_SET_MANAGER_VISIBILITY: "MANAGER_TOGGLE_SEt_MANAGER_VISIBILITY",
    SET_SELECTED_NODE: 'MANAGER_SET_SELECTED_NODE',
    // RELOAD_DISPLAYED_SETS: 'MANAGER_RELOAD_DISPLAYED_SETS',
    // RELOAD: 'MANAGER_RELOAD',
    SET_ACTIVE_ENTITY_IN_SET: 'MANAGER_SET_ACTIVE_ENTITY_IN_SET'
  }
};