/**
 * Created by dmitri on 15/01/16.
 */
'use strict';

export default {
  ActionTypes: {
    TOGGLE_WORKBENCH_MANAGER_VISIBILITY: "TOGGLE_WORKBENCH_MANAGER_VISIBILITY",
    SET_SELECTED_NODE: 'SET_SELECTED_NODE',
    RELOAD_DISPLAYED_WORKBENCHES: 'RELOAD_DISPLAYED_WORKBENCHES',
    BASKET_CHANGE_SELECTION: 'BASKET_CHANGE_SELECTION',
    SET_BASKET: 'SET_BASKET',
    BASKET_REMOVE_ITEM: 'BASKET_REMOVE_ITEM',
    SET_ACTIVE_IN_WORKBENCH: 'SET_ACTIVE_IN_WORKBENCH'
  }
};