/**
 * Created by dmitri on 08/10/15.
 */
'use strict';

export default {
  ActionTypes: {
    TOOL_SET_ACTIVE_TOOL: "TOOL_SET_ACTIVE_TOOL",
    TOOL_CLEAR: "TOOL_CLEAR",
    TOOL_REGISTER: "TOOL_REGISTER",
    TOOL_RUN: "TOOL_RUN",
    TOOL_UPDATE_DATA_DISPLAY: "TOOL_UPDATE_DATA_DISPLAY",
    TOOL_UPDATE_DATA: "TOOL_UPDATE_DATA",
    TOOL_RESET: "TOOL_RESET",
    TOOL_POPUP: "TOOL_POPUP",
    TOOL_SAVE: "TOOL_SAVE"
  }
};