/**
 * Events affecting or generated by view and user-interaction
 *
 * Created by dmitri on 05/10/15.
 */
'use strict';

export default {
  ACTIVE_SET_CHANGE: 'VIEW_activeSetChange',
  ACTIVE_VIEW_CHANGE: 'VIEW_activeViewChange',
  UPDATE_VIEWPORT: "VIEW_updateViewport",
  UPDATE_VIEW_PROPERTIES: 'VIEW_updateViewProperties',
  UPDATE_VIEW_FILTERS: 'VIEW_updateViewFilters',
  FIT_SET_IN_VIEW: "VIEW_fitSetInView",
  UPDATE_LOADER: 'VIEW_updateLoader',
  SELECTION_CHANGE: 'VIEW_selectionChange',
  INSPECTOR_CONTENT_CHANGE: 'VIEW_inspectorContentChange',
  ANNOTATION_LIST_CONTENT_CHANGE: 'VIEW_annotationListContentChange',
  LAB_BENCH_LOAD_PROGRESS: 'VIEW_labBenchLoadProgressChange'
};